[package]

version = "0.1.0"
edition = "2021"
name = "2.substrate_simulator"

[dependencies]

[build-dependencies]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = []

[workspace]

[lib]
path = "src/main.rs"
