[package]
name = "substrate_node_simulator"
version = "0.1.0"
edition = "2018"

[dependencies]
# Substrate framework dependencies
substrate-client = "2.0"
substrate-network = "2.0"
substrate-keyring = "2.0"
sp-runtime = { version = "2.0", features = ["std"] }

[features]
default = ["std"]
std = []
